spring.application.name=gamestore
server.port=8090
spring.datasource.url=jdbc:postgresql://localhost:5432/games
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
jwt.token.validity = 10000
jwt.secret = super_secret_key_yay
