spring.application.name=store
server.port=8090
spring.datasource.url=jdbc:mysql://localhost:1234/online_store_app?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Password123
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
jwt.token.validity = 10000
jwt.secret = super_secret_key_yay
