spring.application.name=store
server.port=8090
server.servlet.context-path=/api
server.error.whitelabel.enabled=false
server.error.path=/error-disabled

# Database
app.db-url=${DB_URL}
app.db-user=${DB_USER}
app.db-password=${DB_PASSWORD}

# Redis
app.redis-host=${REDIS_HOST:localhost}
app.redis-port=${REDIS_PORT:6379}
app.redis-password=${REDIS_PASSWORD:}

# JWT
app.jwt-secret=${JWT_SECRET}
app.jwt-validity=${JWT_VALIDITY:10000}

# Google
app.google-client-id=${GOOGLE_CLIENT_ID}

